pipeline {
  agent any
     tools {
        maven 'maven9'
    }
    stages {
        stage('SCM Checkout') {
            steps{
                git url:'https://github.com/jiyendra/simple-app.git', branch: 'jiyendra/java-docker-web'
            }
        }
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}                        
